# Generated by Django 4.0 on 2021-12-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationallevel',
            name='code',
            field=models.CharField(default='', max_length=300, verbose_name='Код'),
        ),
    ]
