# Generated by Django 4.0 on 2021-12-29 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('time_start', models.TimeField(null=True, verbose_name='Время начала')),
                ('time_end', models.TimeField(null=True, verbose_name='Время окончания занятия')),
                ('note', models.TextField(verbose_name='Примечание')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='timetables.classroom', verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='timetables.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='timetables.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
