# Generated by Django 4.0 on 2021-12-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
    ]
