# Generated by Django 4.0.4 on 2022-07-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0009_lesson_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
    ]
