# Generated by Django 4.0 on 2022-01-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_messengermodel_messengeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengermodel',
            name='code',
            field=models.CharField(default='', max_length=300, unique=True, verbose_name='Код'),
        ),
    ]
