# Generated by Django 4.0 on 2022-01-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_messengermodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengeraccount',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_accounts', to='feedback.profile', verbose_name='Профиль'),
        ),
    ]
