# Generated by Django 4.0 on 2022-01-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0007_lesson_subject'),
        ('feedback', '0004_alter_messengeraccount_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='timetables.group', verbose_name='Текущий выбор группы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_notifications',
            field=models.BooleanField(default=False, verbose_name='Отправлять уведомления?'),
        ),
    ]
