# Generated by Django 4.0 on 2022-01-21 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parsing_enabled', models.BooleanField(default=True, verbose_name='Парсинг активирован?')),
                ('lessons_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала для парсинга занятий')),
                ('lesson_end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Конечная дата для парсинга занятий')),
            ],
            options={
                'verbose_name': 'Настройки парсинга',
                'verbose_name_plural': 'Настройки парсинга',
            },
        ),
    ]
