# Generated by Django 4.0 on 2022-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='telegram_token',
            field=models.CharField(default='', max_length=300, verbose_name='Токен для бота Телеграм'),
        ),
    ]
